#!/bin/sh
#
# PROVIDE: jdownloader
# REQUIRE: LOGIN 
# KEYWORD: shutdown
# $FreeBSD$
#
# Add the following lines to /etc/rc.conf to enable this service:
#
# jdownloader_enable:            Set to NO by default. Set it to YES to enable it.
#                            a path.
# jdownloader_user:              The user account jdownloader daemon runs as
#

. /etc/rc.subr

name="jdownloader"
rcvar=${name}_enable

pidfile=/var/run/JDownloader/JDownloader.pid
command=/usr/pbi/jdownloader-`uname -m`/sbin/jdownloader

load_rc_config $name

jdownloader_user=${jdownloader_user="root"}
_dirs="/var/run/JDownloader /var/log/JDownloader"
start_precmd="mkdir -p $_dirs; touch /var/run/JDownloader/JDownloader.pid; chown -R $jdownloader_user $_dirs; ldconfig -m /usr/pbi/jdownloader-`uname -m`/lib"
#RUN_AS_USER="jdown"

command_args="$jdownloader_args"

jdownloader_stop()
{
        res=1
        echo -n 'Stopping jdownloader.'
        if [ -f "${pidfile}" ]
        then
                kill -KILL $(cat "${pidfile}")
                rm -f ${pidfile}
                res=$?
        else
                killall -KILL jdownloader
                res=$?
        fi

        echo
        return ${res}
}

stop_cmd='jdownloader_stop'
run_rc_command "$1"

# Need to wait for Java to start before getting PID
sleep 2
pgrep -U root -f JDownloader.jar > /var/run/JDownloader/JDownloader.pid
